name: Publish

on:
    schedule:
        - cron: "0 0 * * *"
    workflow_dispatch:

permissions:
    contents: write

env:
    CARGO_TERM_COLOR: always

jobs:
    Build:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: write
        steps:
            - name: Checkout
              uses: actions/checkout@v6
              with:
                  fetch-depth: 0
            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest
            - name: Rust Cache
              uses: Swatinem/rust-cache@v2

            - name: Build
              id: execute
              run: |
                  set +e 

                  bun bump
                  EXIT_CODE=$?

                  set -e

                  if [ $EXIT_CODE -eq 0 ]; then
                    echo "status=continue" >> $GITHUB_OUTPUT
                  elif [ $EXIT_CODE -eq 11 ]; then
                    echo "status=stop" >> $GITHUB_OUTPUT
                    exit 0
                  else
                    echo "Error: Bun failed with unexpected code $EXIT_CODE"
                    exit $EXIT_CODE
                  fi

            - name: Commit files
              if: steps.execute.outputs.status == 'continue'
              run: |
                  cargo update
                  git config --local user.email "2124757129@qq.com"
                  git config --local user.name "Lance"
                  git commit -a -m "Version bump"

            - name: Push changes
              if: steps.execute.outputs.status == 'continue'
              uses: ad-m/github-push-action@master
              with:
                  github_token: ${{ secrets.GH_TOKEN }}
                  branch: ${{ github.ref }}

            - name: Crates.io Auth
              uses: rust-lang/crates-io-auth-action@v1
              if: steps.execute.outputs.status == 'continue'
              id: auth

            - name: Publish Crate
              if: steps.execute.outputs.status == 'continue'
              env:
                  CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
              run: |
                  cargo publish -p lucide-slint --allow-dirty

            - name: Release
              uses: softprops/action-gh-release@v3
              if: steps.execute.outputs.status == 'continue'
              with:
                  tag_name: ${{ env.LUCIDE_VERSION }}
                  target_commitish: ${{ github.ref }}
                  body_path: release-notes.md
                  files: |
                      dist/*
